# app.yaml = application config file
application: coe-dbms-5

version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: studentcrud.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
